# site settings
title: EITI Datathon 2022
description: "Prototype solutions to challenges in energy transition"
email: "eitidatathon@okfn.org"
baseurl: "/eitidatathon2022-guide"
logo: "assets/img/logos/eiti-datathon-gradient.png"
favicon: favicon.ico
repo_address: "school-of-data/eitidatathon2022-guide"
messenger: ""
facebook: ""
twitter: ""
instagram: ""
mastodon: ""
telegram: ""
github: ""

# links
link_qna_asia: "https://us02web.zoom.us/meeting/register/tZ0ofumsrTIpEtwzXsRija-Q4FV8vGduLiAI"
link_qna_euafr: "https://us02web.zoom.us/meeting/register/tZEtc-ygqT8tGtR34ffEYQncacuT387eV3H0"
link_qna_ame: "https://us02web.zoom.us/meeting/register/tZcodeyppz4iHN1FzP3A_8vkqeBxO9oQnBup"
link_submission: https://forms.gle/jn797xoWT37G4JxQ6

# exclude
exclude:
    - .gitignore
    - Gemfile
    - Gemfile.lock

# build settings
markdown: kramdown
highlighter: rouge
# kramdown:
#     input: GFM
#     syntax_highlighter: rouge

collections:
    collection_faq_general:
    collection_faq_application:
    collection_faq_eligibility:
    collection_faq_submission:
    collection_scenario_1_data:
    collection_scenario_2_data:
    collection_scenario_3_data:
    collection_scenario_4_data:
        

# plugins
plugins:
    - github-pages
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-redirect-from
